services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      TOKEN: ${TOKEN}
      BOT_OWNER_ID: ${BOT_OWNER_ID}
      MONGODB_URI: ${MONGODB_URI}
      PORT: ${PORT:-3000}
